export const mockPathways = [
  {
    id: "canada-express-entry",
    country: "Canada",
    flag: "🇨🇦",
    visaName: "Express Entry",
    processingTime: "6 months",
    difficulty: "Medium" as const,
    matchScore: 94,
    description: "Canada's flagship economic immigration system for skilled workers",
    requirements: ["IELTS 7.0+", "Bachelor's degree or higher", "2+ years skilled work experience"],
    reasons: [
      "Your IELTS score meets the threshold",
      "Your occupation is in Canada's high-demand list",
      "Your education level qualifies you for full points",
    ],
    successRate: "82%",
    minSalary: "$55,000 CAD",
    ageBonus: true,
  },
  {
    id: "germany-blue-card",
    country: "Germany",
    flag: "🇩🇪",
    visaName: "EU Blue Card",
    processingTime: "4 months",
    difficulty: "Medium" as const,
    matchScore: 87,
    description: "Residence permit for highly qualified non-EU workers",
    requirements: ["Recognized degree", "Job offer in Germany", "Minimum salary €43,800"],
    reasons: [
      "Your qualification meets EU Blue Card standards",
      "High demand for your occupation in Germany",
      "Processing time aligns with your 6-month timeline",
    ],
    successRate: "79%",
    minSalary: "€43,800",
    ageBonus: false,
  },
  {
    id: "portugal-d7",
    country: "Portugal",
    flag: "🇵🇹",
    visaName: "D7 Passive Income Visa",
    processingTime: "3 months",
    difficulty: "Easy" as const,
    matchScore: 81,
    description: "For those with passive income, remote workers, and retirees",
    requirements: ["Proof of passive income", "€760/month minimum", "Clean criminal record"],
    reasons: [
      "Fastest processing time of your options",
      "No job offer required",
      "Path to permanent residency in 5 years",
    ],
    successRate: "91%",
    minSalary: "€760/month",
    ageBonus: false,
  },
];

export const mockDocuments = [
  {
    id: "passport",
    name: "Valid Passport",
    description: "Must be valid for at least 6 months beyond your intended stay",
    required: true,
    canGenerate: false,
  },
  {
    id: "ielts",
    name: "IELTS or CELPIP Results",
    description: "Official language test results issued within the last 2 years",
    required: true,
    canGenerate: false,
  },
  {
    id: "wes",
    name: "Educational Credential Assessment (WES)",
    description: "Foreign credential evaluation by World Education Services",
    required: true,
    canGenerate: false,
  },
  {
    id: "work-experience",
    name: "Proof of Work Experience",
    description: "Employment letter on company letterhead with dates and duties",
    required: true,
    canGenerate: true,
  },
  {
    id: "police-cert",
    name: "Police Certificate",
    description: "Criminal record check from each country you've lived in for 6+ months",
    required: true,
    canGenerate: false,
  },
];

export const mockApplicationSteps = [
  {
    id: "gather-docs",
    title: "Gather Documents",
    status: "complete" as const,
    description: "Collect all required supporting documents for your application",
    explanation: "You've already uploaded most of your documents. Just the police certificate is missing.",
    documents: ["passport", "ielts", "wes"],
    canGenerate: false,
  },
  {
    id: "language-test",
    title: "Language Test",
    status: "complete" as const,
    description: "Complete an approved English or French language test",
    explanation: "Your IELTS score of 7.5 is well above the minimum threshold of 6.0.",
    documents: ["ielts"],
    canGenerate: false,
  },
  {
    id: "credential-assessment",
    title: "Credential Assessment",
    status: "in_progress" as const,
    description: "Have your foreign credentials evaluated by a designated organization",
    explanation: "Your WES evaluation is in progress. This typically takes 7–10 business days.",
    documents: ["wes"],
    canGenerate: false,
  },
  {
    id: "express-entry-profile",
    title: "Create Express Entry Profile",
    status: "not_started" as const,
    description: "Submit your profile to the Express Entry pool and receive a CRS score",
    explanation: "Once your credential assessment is complete, you can create your profile online at IRCC's portal.",
    documents: [],
    canGenerate: true,
  },
  {
    id: "submit-eoi",
    title: "Submit Expression of Interest",
    status: "not_started" as const,
    description: "Express your interest in immigrating to Canada",
    explanation: "Your Expression of Interest will be ranked against other candidates using the Comprehensive Ranking System.",
    documents: [],
    canGenerate: false,
  },
  {
    id: "receive-ita",
    title: "Receive Invitation to Apply",
    status: "not_started" as const,
    description: "If selected, you'll receive an Invitation to Apply for permanent residence",
    explanation: "Based on your CRS score of approximately 478, you have a strong chance of receiving an ITA in the next 2-3 draws.",
    documents: [],
    canGenerate: false,
  },
  {
    id: "submit-application",
    title: "Submit PR Application",
    status: "not_started" as const,
    description: "Complete and submit your full permanent residence application",
    explanation: "You'll have 60 days from your ITA to submit a complete application.",
    documents: ["passport", "police-cert", "work-experience"],
    canGenerate: true,
  },
  {
    id: "medical-exam",
    title: "Medical Examination",
    status: "not_started" as const,
    description: "Complete a medical exam with a designated physician",
    explanation: "Schedule your medical exam as soon as you receive your ITA — results are valid for 12 months.",
    documents: [],
    canGenerate: false,
  },
  {
    id: "receive-pr",
    title: "Receive PR Confirmation",
    status: "not_started" as const,
    description: "Receive your Confirmation of Permanent Residence and PR card",
    explanation: "Once approved, you'll receive your COPR. You must land in Canada before the expiry date.",
    documents: [],
    canGenerate: false,
  },
];

export const mockProfile = {
  nationality: "Indian",
  destination: "Canada",
  purpose: "Work",
  occupation: "Software Engineer",
  family: "Spouse + 1 child",
  timeline: "6 months",
};

export const mockOnboardingQuestions = [
  {
    id: "education",
    question: "What is your highest level of education?",
    options: ["High school", "Bachelor's degree", "Master's degree", "PhD", "Trade certification"],
  },
  {
    id: "language-test",
    question: "Do you have an official language test result?",
    options: ["IELTS 6.0–6.5", "IELTS 7.0–7.5", "IELTS 8.0+", "CELPIP 7–8", "TEF equivalent", "Not yet"],
  },
  {
    id: "family",
    question: "Are you applying alone or with family members?",
    options: ["Applying alone", "With spouse/partner", "With spouse + children", "With children only"],
  },
  {
    id: "timeline",
    question: "What is your target timeline for the move?",
    options: ["As soon as possible", "Within 6 months", "6–12 months", "1–2 years", "Just exploring"],
  },
  {
    id: "prior-applications",
    question: "Have you previously applied for immigration to any country?",
    options: ["No, first time", "Yes, approved", "Yes, refused", "Yes, currently pending"],
  },
];
